apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: favobps
  labels:
    partner: FahrradVogel
    product: favobps
spec:
  selector:
    app: frontend
  ports:
  - name: frontend-port
    targetPort: 8080
    protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-frontend
  namespace: favobps
  labels:
    partner: FahrradVogel
    product: favobps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        partner: FahrradVogel
        product: favobps
      annotations:
        a8r.io/description: Deployment of service 'frontend'
        a8r.io/owner: '@me'
        composedServiceConfig: |
          runtimeEnvironment=kubernetes
          logoPath=https://my-fileserver.net/partner/favo/vogel.png
    spec:
      containers:
      - name: cnt-frontend
        env:
        - name: CONFIG_FILE_PATH
          value: /app/config/config.properties
        image: http://myregistry.net/services/frontend:1.4.19
        imagePullPolicy: Always
        resources:
          requests:
            memory: 64M
          limits:
            memory: 64M
        volumeMounts:
        - name: vlm-config
          mountPath: /app/config
      volumes:
      - name: vlm-config
        downwardAPI:
          items:
          - path: config.properties
            fieldRef:
              fieldPath: metadata.annotations['composedServiceConfig']
